sudo:              required
language:          python

services:
  - docker


before_install:
  - sudo apt-get update
  - docker version
  - docker-compose version
  - echo $CI
  - echo $SECRET_KEY
  - python test.py

  
install:
  - docker-compose build
  - docker-compose up -d

script:
  - wget localhost:80
  #TODO(gocarlos): add here some tests

after_script:
  - docker-compose down
