sudo: required
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - sudo pip install docker-compose
  - docker —version
  - echo “ENV GIT_SHA ${TRAVIS_COMMIT}” >> Dockerfile
  - docker-compose up

  #TODO(gocarlos): add here some tests
  
after_script:
  - docker-compose down
