version: '2'


services:
  db:
    image: postgres
  web:
    environment:
      SECRET_KEY:
    build: .
    command: python3 django_volumen/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
