version: '2'

environment:
  SECRET_KEY:

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 django_volumen/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
