# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('discription', models.CharField(max_length=1000)),
                ('duration', models.IntegerField(default=0)),
                ('played_time', models.IntegerField(default=0)),
                ('times_played', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('discription', models.CharField(max_length=1000)),
                ('cover', models.CharField(max_length=500)),
                ('nbr_episodes', models.IntegerField(default=0)),
                ('nbr_episodes_played', models.IntegerField(default=0)),
                ('last_refreshed', models.IntegerField(default=0)),
            ],
        ),
    ]
