# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_browser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_id',
            field=models.IntegerField(default=0),
        ),
    ]
